[BE-97] 지원 현황 및 면접 기록 조회 API 정렬 로직 개선, 검색 쿼리 추가
JNU-econovation/econo-recruit pull request #274
Opened 2024-09-23 05:58 UTC by Profile-exe

### 개요
close #263 #272 

###  작업사항
- 정렬을 위한 쿼리 파라미터 이름을 `order`로 통일
- 지원 현황 조회, 면접 기록 조회 API에 `searchKeyword` 쿼리 파라미터를 추가해 별도의 검색 API 엔드포인트를 사용하지 않음
- 전체 결과에 대한 정렬 이후 페이징을 수행해 페이지별 일관성 확보

### 변경로직

- `AnswerService`
  ```java
  @Transactional(readOnly = true)
  public AnswersResponseDto execute(Integer year, Integer page, String sortType, String searchKeyword) {
      PageInfo pageInfo = getPageInfo(year, page, searchKeyword);
      List<MongoAnswer> sortedResult = answerAdaptor.findByYearAndSearchKeyword(year, page, sortType, searchKeyword);
  
      List<Map<String, Object>> qnaMapList = getQnaMapListWithIdAndPassState(sortedResult);
  
      if (qnaMapList.isEmpty()) {
          return AnswersResponseDto.of(Collections.emptyList(), pageInfo);
      }
      return AnswersResponseDto.of(qnaMapList, pageInfo);
  }
  ```

- `RecordService`
  ```java
  @Override
  public RecordsViewResponseDto execute(Integer page, Integer year, String sortType, String searchKeyword) {
      List<Record> result = recordLoadPort.findAll();
      List<String> applicantIds = result.stream().map(Record::getApplicantId).toList();
  
      List<MongoAnswer> applicants;
      if (sortType.equals("score")) {
          applicants = applicantQueryUseCase.execute(year, sortType, searchKeyword, applicantIds);
      } else {
          applicants = applicantQueryUseCase.execute(page, year, sortType, searchKeyword, applicantIds);
      }
  
      if (result.isEmpty() || applicants.isEmpty()) {
          return createEmptyResponse(new PageInfo(0, page));
      }
  
      Map<String, Integer> yearByAnswerIdMap = applicants.stream().collect(Collectors.toMap(MongoAnswer::getId, MongoAnswer::getYear));
  
      applicantIds = applicants.stream().map(MongoAnswer::getId).toList();    // 검색 결과에 따라 applicantIds 재할당
      Map<String, Double> scoreMap = getScoreMap(year, applicantIds, yearByAnswerIdMap);
  
      result = result.stream().filter(record -> year == null ||
                      Optional.ofNullable(record.getApplicantId())
                              .map(yearByAnswerIdMap::get)
                              .map(y -> y.equals(year))
                              .orElse(false)
              )
              .toList();
  
      List<Record> records;
      if (sortType.equals("score")) {
          records = sortRecordsByScoresDesc(result, scoreMap, page);
      } else {
          records = sortRecordsByApplicantsAndSortType(result, applicants);
      }
  
      PageInfo pageInfo = applicantQueryUseCase.getPageInfo(year, page, searchKeyword);
      return RecordsViewResponseDto.of(pageInfo, records, scoreMap, applicants);
  }
  ```

### reference
-

2024-09-23 07:07 UTC, LJH098 requested changes

2024-09-23 07:07 UTC, LJH098 commented on server/Recruit-Api/src/main/java/com/econovation/recruit/api/applicant/service/ApplicantService.java
> +    }
getQnaMapListWithIdAndPassState 를 따로 나눈 이유가 
id랑 pass_state_key만 따로 넣을 수 도 있어서 분리 한 것일까요? (정렬 없이)

2024-09-23 07:07 UTC, LJH098 commented on server/Recruit-Api/src/main/java/com/econovation/recruit/api/interviewer/service/InterviewersService.java
> +        }
interviewers가 null 이라면 즉, 빈 배열이라면 아래 return return interviewers.stream().map(InterviewerResponseDto::from).toList(); 에서 NPE가 발생 할 것 같은데 
이 부분 예외 처리를 따로 하면 좋을 것 같아요

2024-09-23 07:07 UTC, LJH098 commented on server/Recruit-Api/src/main/java/com/econovation/recruit/api/interviewer/service/InterviewersService.java
> +        }
실제로 지금 상황에서 interviewer 가 아무도 없을 때 500에러가 떠서 운영 환경에서 사용자는 아무 액션을 받지못함 (FE가 처리를 못하니까)

2024-09-23 07:07 UTC, LJH098 commented on server/Recruit-Api/src/main/java/com/econovation/recruit/api/record/service/RecordService.java
> +    }
저는 Dto 클래스 안에 static으로 Dto를 만드는 정적 팩토리 메서드를 사용하는데 
service단에 private으로 Dto 만드는 메서드를 사용하시는 이유가 있을까요??

어떤 관점에서 service에 작성을 한건지 궁금합니다.

2024-09-23 07:07 UTC, LJH098 commented on server/Recruit-Api/src/main/java/com/econovation/recruit/api/record/service/RecordService.java
>      }
왜 메소드 명이 getScoreMap이죠? 이렇게 메소드 분리해서 책임을 명확히 분리할 거면 이 메소드를 사용하는 곳에서 이 메소드가 어떤 
역할을 하는지 직관적이어야 합니다. (그래야 다른 사람이 코드를 읽을 때 파악하기 쉬움)

그런데 이 메소드 역할은 Score를 가져와서 평균을 내는 작업이네요

2024-09-23 07:07 UTC, LJH098 commented on server/Recruit-Api/src/main/java/com/econovation/recruit/api/record/service/RecordService.java
> +    }
위에 sortType이 score인걸 확인하고 있는데 왜 아래서 또 확인을하고 적용하는 거죠? 한꺼번에 하면 안되는 이유가 있나요?
왜 두번 체크하는지 모르겠습니다.

2024-09-23 07:12 UTC, Profile-exe commented on server/Recruit-Api/src/main/java/com/econovation/recruit/api/record/service/RecordService.java
> +    }
기존에 메서드 내부에 작성된 로직인데, DTO 클래스에 넣는게 좋다고 생각합니다! 반영하겠습니다.

2024-09-23 07:44 UTC, Profile-exe commented on server/Recruit-Api/src/main/java/com/econovation/recruit/api/applicant/service/ApplicantService.java
> +    }
넵 맞습니다. `qna` 맵을 추출하고 여기에 `id`와 `passState`를 넣기 때문에 메서드로 분리했습니다.

2024-09-23 07:47 UTC, Profile-exe commented on server/Recruit-Api/src/main/java/com/econovation/recruit/api/interviewer/service/InterviewersService.java
> +        }
확인했습니다! 해당 부분은 [9591722](https://github.com/JNU-econovation/econo-recruit/pull/274/commits/9591722ccbdbfe2d4b673659fb304c2cbe413405) 커밋에 반영했습니다.

```java
@Override
public List<InterviewerResponseDto> findAll(String sortType) {
    List<Interviewer> interviewers = interviewerLoadPort.findAll();
    if (interviewers != null && !interviewers.isEmpty()) {
        interviewerSortHelper.sort(interviewers, sortType);
        return interviewers.stream().map(InterviewerResponseDto::from).toList();
    }
    return Collections.emptyList();
}
```

2024-09-23 08:44 UTC, rlajm1203 commented on server/Recruit-Api/src/main/java/com/econovation/recruit/api/applicant/controller/ApplicantController.java
> +            @RequestParam(required = false) String searchKeyword) {
이 부분은 searchKeyword가 null일 경우에는 전체 조회를 하기 위한 용도인 거죠?

그리고 혹시 @ParameterObject 대신 @RequestParam을 사용하신 이유가 따로 있을까요? ㅎㅎ

2024-09-23 08:47 UTC, rlajm1203 commented on server/Recruit-Api/src/main/java/com/econovation/recruit/api/record/service/RecordService.java
> +    }
엇 이 부분은 제가 이슈로 작성한 BE-103 내용이긴 한데, 명덕님께서 해결해주셨네요!

BE-103 이슈는 제가 당장 해결하지 못할 것 같아서 Assignee를 저로 하지는 않았지만 명덕님께서 해결하셨다면

해결하신 이슈에 Assignee 설정 부탁드리겠습니다!

2024-09-23 11:33 UTC, Profile-exe commented on server/Recruit-Api/src/main/java/com/econovation/recruit/api/applicant/controller/ApplicantController.java
> +            @RequestParam(required = false) String searchKeyword) {
`@ParameterObject`를 사용하면 swagger에서 required 필드로 보여 필수로 입력해야 한다고 인지됩니다! 
그래서 `@RequestParam`의 `required` 값을 `false`로 두어 필수 값이 아님을 명시했습니다.

2024-09-23 11:34 UTC, Profile-exe commented on server/Recruit-Api/src/main/java/com/econovation/recruit/api/record/service/RecordService.java
> +    }
넵 `Assignee` 설정 완료했습니다!

2024-09-23 11:56 UTC, Profile-exe commented on server/Recruit-Api/src/main/java/com/econovation/recruit/api/record/service/RecordService.java
> +    }
[b4dc8b6](https://github.com/JNU-econovation/econo-recruit/pull/274/commits/b4dc8b688cc214c6699ce2f0d7499d7840cf114a) 커밋에 반영했습니다!

2024-09-23 12:04 UTC, Profile-exe commented on server/Recruit-Api/src/main/java/com/econovation/recruit/api/record/service/RecordService.java
>      }
함수 내부 로직으로 있던 코드인데, 변수명이 `scoreMap`이라 그대로 사용했습니다.
[4b0bf42](https://github.com/JNU-econovation/econo-recruit/pull/274/commits/4b0bf426b8febeae913ebaaac62a33f4ce6bc207) 커밋에서 `calculateAverageScoresByApplicant`로 메서드명 변경했습니다!

2024-09-23 14:39 UTC, Profile-exe commented on server/Recruit-Api/src/main/java/com/econovation/recruit/api/record/service/RecordService.java
> +    }
[a613304](https://github.com/JNU-econovation/econo-recruit/pull/274/commits/a61330427f7ed5d379713aa0480af5cac3ea6ed8) 해당 커밋에서 공통로직을 메서드로 추출 후 분기를 하나로 처리했습니다!

2024-09-23 14:51 UTC, Profile-exe commented on server/Recruit-Api/src/main/java/com/econovation/recruit/api/record/service/RecordService.java
> +    }
[dad5f5a](https://github.com/JNU-econovation/econo-recruit/pull/274/commits/dad5f5a0074849918142ccbc12a658258d8f9b75) 커밋에서 기수별 면접기록 필터링 로직도 메서드로 추출했습니다.

2024-09-24 03:01 UTC, LJH098 approved these changes

2024-09-24 03:01 UTC, merged